import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB

from app.db.tables import metadata

listings_table = sa.Table(
    "listings",
    metadata,
    sa.Column("id", sa.UUID(), primary_key=True, server_default=sa.text("gen_random_uuid()")),
    sa.Column(
        "region_id",
        sa.UUID(),
        sa.ForeignKey("regions.id", ondelete="CASCADE"),
        nullable=False,
    ),
    sa.Column(
        "area_id",
        sa.UUID(),
        sa.ForeignKey("areas.id", ondelete="SET NULL"),
        nullable=True,
    ),
    sa.Column("kind", sa.Text(), nullable=False),
    sa.Column("deal_type", sa.Text(), nullable=False),
    sa.Column("building_name", sa.Text(), nullable=True),
    sa.Column("deposit", sa.Integer(), nullable=True),
    sa.Column("monthly_rent", sa.Integer(), nullable=False, server_default=sa.text("0")),
    sa.Column("deal_amount", sa.Integer(), nullable=True),
    sa.Column("area_m2", sa.Numeric(8, 2), nullable=True),
    sa.Column("floor", sa.Integer(), nullable=True),
    sa.Column("jibun", sa.Text(), nullable=True),
    sa.Column("road_addr", sa.Text(), nullable=True),
    sa.Column("build_year", sa.Integer(), nullable=True),
    sa.Column("umd_name", sa.Text(), nullable=True),
    sa.Column("deal_date", sa.Date(), nullable=True),
    sa.Column("lat", sa.Numeric(9, 6), nullable=True),
    sa.Column("lng", sa.Numeric(9, 6), nullable=True),
    sa.Column("source_payload", JSONB(), nullable=True),
    sa.Column("flood_risk", sa.Boolean(), nullable=True),
    sa.Column("flood_year", sa.Integer(), nullable=True),
    sa.Column("estimated_kind", sa.Text(), nullable=True),
    sa.Column("dedup_hash", sa.CHAR(64), nullable=False, unique=True),
    sa.Column("house_type_raw", sa.Text(), nullable=True),
    sa.Column("pre_deposit", sa.Integer(), nullable=True),
    sa.Column("pre_monthly_rent", sa.Integer(), nullable=True),
    sa.Column("contract_type", sa.Text(), nullable=True),
    sa.Column("use_rr_right", sa.Boolean(), nullable=True),
    sa.Column("apt_seq", sa.Text(), nullable=True),
    sa.Column(
        "created_at",
        sa.DateTime(timezone=True),
        nullable=False,
        server_default=sa.text("now()"),
    ),
    sa.Index("ix_listings_region_deal_type", "region_id", "deal_type"),
    sa.Index("ix_listings_area_deal_type", "area_id", "deal_type"),
    sa.Index("ix_listings_kind_dtype_date", "kind", "deal_type", "deal_date"),
    sa.Index("ix_listings_building_area", "building_name", "area_id"),
    sa.Index("ix_listings_deal_date", "deal_date"),
)
