import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ARRAY, JSONB

from app.db.tables import metadata

support_programs_table = sa.Table(
    "support_programs",
    metadata,
    sa.Column("id", sa.UUID(), primary_key=True, server_default=sa.text("gen_random_uuid()")),
    sa.Column("plcy_no", sa.Text(), nullable=False, unique=True),
    sa.Column("name", sa.Text(), nullable=False),
    sa.Column("category_l", sa.Text(), nullable=True),
    sa.Column("category_m", sa.Text(), nullable=True),
    sa.Column("age_min", sa.Integer(), nullable=True),
    sa.Column("age_max", sa.Integer(), nullable=True),
    sa.Column("income_min", sa.Integer(), nullable=True),
    sa.Column("income_max", sa.Integer(), nullable=True),
    sa.Column("marriage_cd", sa.Text(), nullable=True),
    sa.Column("support_amount", sa.Integer(), nullable=True),
    sa.Column("support_text", sa.Text(), nullable=True),
    sa.Column("apply_url", sa.Text(), nullable=True),
    sa.Column("start_date", sa.Date(), nullable=True),
    sa.Column("end_date", sa.Date(), nullable=True),
    sa.Column("region_zip_codes", sa.Text(), nullable=True),
    sa.Column("raw", JSONB(), nullable=True),
    sa.Column("card_key", sa.Text(), nullable=True),
    sa.Column("loan_limit", sa.Integer(), nullable=True),
    sa.Column("deposit_limit", sa.Integer(), nullable=True),
    sa.Column("rent_limit", sa.Integer(), nullable=True),
    sa.Column("income_median_pct", sa.Integer(), nullable=True),
    sa.Column("income_max_annual", sa.Integer(), nullable=True),
    sa.Column("income_max_monthly_wan", sa.Integer(), nullable=True),
    sa.Column("housing_types", ARRAY(sa.Text()), nullable=True),
    sa.Column("rules_extracted", JSONB(), nullable=True),
    # LLM 추출 6개
    sa.Column("monthly_amount_wan", sa.Integer(), nullable=True),
    sa.Column("duration_months", sa.Integer(), nullable=True),
    sa.Column("asset_limit_wan", sa.Integer(), nullable=True),
    sa.Column("support_type", sa.Text(), nullable=True),
    sa.Column("is_homeless_required", sa.Boolean(), nullable=True),
    sa.Column("separate_from_parents", sa.Boolean(), nullable=True),
    # raw 메타 10개
    sa.Column("agency_name", sa.Text(), nullable=True),
    sa.Column("operating_agency", sa.Text(), nullable=True),
    sa.Column("recruit_count", sa.Integer(), nullable=True),
    sa.Column("recruit_unlimited", sa.Boolean(), nullable=True),
    sa.Column("submission_documents", sa.Text(), nullable=True),
    sa.Column("screening_method", sa.Text(), nullable=True),
    sa.Column("participation_exclusion", sa.Text(), nullable=True),
    sa.Column("reference_urls", ARRAY(sa.Text()), nullable=True),
    sa.Column("keyword_name", sa.Text(), nullable=True),
    sa.Column("view_count", sa.Integer(), nullable=True),
    # 추가 코드 4개
    sa.Column("major_code", sa.Text(), nullable=True),
    sa.Column("job_code", sa.Text(), nullable=True),
    sa.Column("school_code", sa.Text(), nullable=True),
    sa.Column("business_code", sa.Text(), nullable=True),
    sa.Column(
        "created_at",
        sa.DateTime(timezone=True),
        nullable=False,
        server_default=sa.text("now()"),
    ),
    sa.Column(
        "updated_at",
        sa.DateTime(timezone=True),
        nullable=False,
        server_default=sa.text("now()"),
    ),
    sa.Index("ix_support_programs_category_m", "category_m"),
    sa.Index("ix_support_programs_age", "age_min", "age_max"),
    sa.Index("ix_support_programs_card_key", "card_key"),
)
